# Generated by Django 3.0.7 on 2020-08-13 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200812_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_query_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
